# Generated by Django 5.2 on 2025-08-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('firstname', models.TextField()),
                ('middlename', models.TextField()),
                ('lastname', models.TextField()),
                ('suffix', models.TextField(null=True)),
                ('email', models.TextField()),
                ('birthday', models.TextField()),
                ('phone_number', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='user_profile/')),
                ('department', models.TextField()),
                ('job_title', models.TextField()),
                ('employee_type', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LEAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('leave_type', models.TextField(blank=True)),
                ('commutation', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('details_of_leave', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
