# Generated by Django 5.2 on 2025-08-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
