# Generated by Django 5.2 on 2025-08-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
