# Generated by Django 5.2 on 2025-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_statusnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.TextField(null=True),
        ),
    ]
