# Generated by Django 5.2 on 2025-08-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnotif',
            name='current_status',
            field=models.TextField(null=True),
        ),
    ]
