# Generated by Django 5.2 on 2025-09-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_statusnotif_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusnotif',
            name='user',
        ),
        migrations.AddField(
            model_name='statusnotif',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LEAVEs', to='users.leave'),
        ),
    ]
