# Generated by Django 5.2 on 2025-09-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_statusnotif_user_statusnotif_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusnotif',
            old_name='admin',
            new_name='user',
        ),
    ]
