# Generated by Django 5.2 on 2025-09-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_types',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
