# Generated by Django 5.2 on 2025-09-21 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_leave_types_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(null=True)),
                ('leave_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.leave_types')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
