# Generated by Django 5.2 on 2025-09-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_leavetypedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='specify',
            field=models.TextField(blank=True),
        ),
    ]
