# Generated by Django 5.2 on 2025-09-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_leave_specify'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='credit',
            field=models.TextField(default='1.25', null=True),
        ),
    ]
