# Generated by Django 5.2 on 2025-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_users_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_credit_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
