# Generated by Django 5.1.4 on 2025-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_users_last_credit_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='inclusive_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='number_of_days_applied',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
