# Generated by Django 5.1.4 on 2025-09-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_leave_inclusive_dates_leave_number_of_days_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='details_of_leave',
        ),
    ]
