# Generated by Django 5.1.4 on 2025-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_leave_details_of_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='attached_files/'),
        ),
    ]
