# Generated by Django 5.1.4 on 2025-09-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_leave_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
    ]
