# Generated by Django 5.1.4 on 2025-09-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_leave_comment_remove_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
