# Generated by Django 5.1.4 on 2025-09-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_leave_end_date_leave_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.leavetypedetails'),
            preserve_default=False,
        ),
    ]
