# Generated by Django 5.1.4 on 2025-09-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_leave_leave_type_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_type_details',
            new_name='leave_details',
        ),
    ]
