# Generated by Django 5.1.4 on 2025-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_leave_type_details_leave_leave_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_of_request',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
