# Generated by Django 5.1.4 on 2025-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_leave_date_of_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_of_request',
            field=models.DateField(auto_now_add=True),
        ),
    ]
