# Generated by Django 5.1.4 on 2025-09-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_leave_date_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='tried',
            field=models.TextField(blank=True),
        ),
    ]
