# Generated by Django 5.1.4 on 2025-09-24 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_leave_tried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='tried',
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_of_request',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
