# Generated by Django 5.1.4 on 2025-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_leave_tried_alter_leave_date_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='disapproved_due_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='recommendation_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='recommendation_for_disapproval_due_to',
            field=models.TextField(blank=True),
        ),
    ]
