# Generated by Django 5.1.4 on 2025-09-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_leave_approved_for_leave_disapproved_due_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='inclusive_dates',
        ),
    ]
