# Generated by Django 5.1.4 on 2025-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_leave_inclusive_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date_of_action',
            field=models.TextField(blank=True),
        ),
    ]
