# Generated by Django 5.1.4 on 2025-10-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_leave_createdat_alter_leave_types_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='suffix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
