# Generated by Django 5.1.4 on 2025-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_users_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='credit',
            field=models.TextField(default='10.0', null=True),
        ),
    ]
