# Generated by Django 5.1.4 on 2025-10-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_users_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
