# Generated by Django 5.1.4 on 2025-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_users_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
