# Generated by Django 5.2.6 on 2025-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_users_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='disapproved_due_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='recommendation_for_disapproval_due_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
