# Generated by Django 5.2 on 2025-12-11 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_leave_approved_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMonthlyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('remaining_credits', models.FloatField(default=0.0)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.leave_types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
