# Generated by Django 5.2 on 2025-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_usermonthlybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='hr_balance_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_balance_vl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_certification_as_of',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_less_this_application_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_less_this_application_vl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_total_earned_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_total_earned_vl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
