# Generated by Django 5.2.6 on 2025-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_leave_hr_balance_sl_leave_hr_balance_vl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='recommendation_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
