from django.urls import path
from . import views
urlpatterns = [
    path("",views.login, name="login" ),
    path("user/", views.user_dashboard, name="user_dasboard"),
    path("user/security", views.security, name="security"),
    path("user/change_password", views.change_password, name="change_password"),
    path("user/profile/", views.user_employee_profile, name="user_employee_profile"),
    path("user/omnibus/", views.user_omnibus, name="omnibus"),
    path("user/instructions/", views.user_instruction, name="instructions"),
    path("admin/", views.admin, name="admins"),
    path("admin/manage_users", views.admin_manage_users, name="admin_manage_users"),
    path("admin/edit_user", views.admin_edit_user, name="admin_edit_user"),
    path("admin/leave_types", views.leave_types, name="leave_types"),
    path("logout/", views.logout, name="logout"),
    path("user/delete", views.delete_user, name="delete_user"),
    path("user/delete_selected", views.delete_selected_user, name="delete_selected"),
    
    # hr
    path("hr/", views.hr_dasboard, name="hr"),
    path("hr/request", views.hr_request, name="hr_request"),
    path("hr/request/employee-profile/<int:userID>", views.hr_emp_profile, name="emp-profile"),
    path("api/hr/request", views.getRequestFilter),
    path("api/hr/leave", views.getLeaveReq),
    path("api/hr/leave_ledger/<int:user_id>", views.leave_ledger),
    path("api/hr/action", views.action, name="action"),   
    path("api/hr/approved", views.approved_leave_request),   
    path("api/hr/reject", views.rejected_leave_request),
    path("api/hr/ongoing", views.apiOngoing),
    path("api/user/delete", views.user_delete_leave),
    path("api/admin/getLeaveType", views.getLeaveTypes),
    path("api/admin/addLeaveType", views.addLeaveType),
    path("api/admin/deleteLeaveType", views.deleteLeaveType),
    path("api/user/getDetails", views.getDetails),
]